version: '3.8'
services:
  pg14:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 'root'
    volumes:
      - type: bind
        source: C:\tmp\sql\data
        target: /var/lib/postgresql/data
    ports:
      - '5567:5432'